# Generated by Django 3.2.5 on 2021-08-01 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mail', models.CharField(max_length=200)),
                ('call', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=200)),
                ('instrument', models.CharField(max_length=200)),
                ('job', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('singer', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=200)),
                ('words', models.TextField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
