# Generated by Django 3.2.5 on 2021-08-01 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='call',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='application',
            name='genre',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='application',
            name='instrument',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='application',
            name='job',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='application',
            name='link',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='application',
            name='location',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='application',
            name='mail',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='application',
            name='singer',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='application',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='application',
            name='words',
            field=models.TextField(default=''),
        ),
    ]
